import type { NextPage } from "next";
import Head from "next/head";
import { Box } from "@mui/system";
import { red } from "@mui/material/colors";

import { List } from "../src/components/List";

import { useGetData } from "../src/data/hooks/index";
import { useState } from "react";

const Home: NextPage = (data: { results: [] }) => {
  const [results, setResults] = useState(data.results);

  return (
    <>
      <Head>
        <title>Marvel Universe - PP Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ width: 1, padding: 4, bgcolor: red[100] }}>
        <List results={results} />
      </Box>
    </>
  );
};

Home.getInitialProps = async (context) => {
  const { getCharacters } = useGetData();

  const data: { data: {} } = await getCharacters();
  return data.data;
};

export default Home;
