import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import md5 from "crypto-js/md5";

import { useEffect, useState } from "react";
import {
  Container,
  Card,
  CardHeader,
  CardContent,
  Typography,
  CardMedia,
  CardActions,
  Button,
  IconButton,
} from "@mui/material";
import { Box } from "@mui/system";
import { red } from "@mui/material/colors";

const BASE_URL = "http://gateway.marvel.com/v1/public";
const PUBLIC_KEY = "77024ac9aa61d221928c3863a557a749";
const PRIVATE_KEY = "xxx";

const Home: NextPage = () => {
  let [data, setData] = useState([]);

  let TIME = Number(new Date());
  let HASH = md5(TIME + PRIVATE_KEY + PUBLIC_KEY);

  useEffect(() => {
    axios
      .get(
        `${BASE_URL}/characters?ts=${TIME}&apikey=${PUBLIC_KEY}&hash=${HASH}`
      )
      .then((response) => setData(response.data.data.results))
      .catch((err) => setData(err));
  }, []);

  return (
    <>
      <Head>
        <title>Marvel Universe - PP Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ width: 1, padding: 4, bgcolor: red[100] }}>
        <Container
          maxWidth="lg"
          sx={{
            display: "flex",
            flexDirection: "row",
            flexWrap: "wrap",
            justifyContent: "center",
          }}
        >
          {data !== undefined
            ? data.map(({ id, name, description, thumbnail }) => (
                <Card sx={{ maxWidth: 207, margin: 2, height: 627 }}>
                  <CardHeader id={id} title={name} subheader="" />
                  <CardMedia
                    component="img"
                    height="194"
                    image={`${thumbnail.path}.${thumbnail.extension}`}
                    alt={name}
                  />
                  <CardContent>
                    <Typography variant="body2" color="text.secondary">
                      <Box sx={{ lineHeight: 2 }}>
                        {!description
                          ? "This character doesn't have a description"
                          : description}
                      </Box>
                    </Typography>
                  </CardContent>
                  <CardActions sx={{ justifyContent: "space-between" }}>
                    <IconButton arial-label="add to favorites">❤</IconButton>
                    <Button>Learn More</Button>
                  </CardActions>
                </Card>
              ))
            : `${JSON.stringify(data)}`}
        </Container>
      </Box>
    </>
  );
};

export default Home;
